apiVersion: v1
kind: Service
metadata:
  name: vault-ui
  namespace: vault
spec:
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: vault
    component: server
  type: ClusterIP
